config/routes.rb
BecauseWeCare::Application.routes.draw do
  root :to => 'welcome#index'

  get "/welcome", to: "welcome#index", as: :welcome

  get "/bwc", to: "bwc#index", as: :bwc
  get "/bwc/about-us", to: "bwc#about_us", as: :bwc_aboutus
  get "/bwc/contact", to: "bwc#contact", as: :bwc_contact

  get "/ant", to: "ant#index", as: :ant
  get "/ant/about-us", to: "ant#about_us", as: :ant_aboutus
  get "/ant/contact", to: "ant#contact", as: :ant_contact

end

app/controllers/ant_controller.rb
class AntController < ApplicationController

  def index

  end

  def about_us

  end

  def contact

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bwc_controller.rb
class BwcController < ApplicationController

  def index

  end

  def about_us

  end

  def contact

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bwc/index.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">

    <a class="brand" href="/bwc">Because We Care</a>

    <ul class="nav navbar-nav">
      <li><%= link_to 'Home', welcome_path, class: "nav-link" %></li>
      <li><%= link_to 'About Us', bwc_aboutus_path, class: "nav-link" %></li>
      <li><%= link_to 'Contact Information', bwc_contact_path, class: "nav-link" %></li>
      <li><%= link_to 'Our Other Location', ant_path, class: "nav-link" %></li>
    </ul>
  </div>
</div>

<div id="wrapper">

<div id="navbar-compensate"></div>

<div id="about-facility-container">

  <div class="new-row" id="row-number-1">
    <div class="facility-profile two-in-row details-box">
      <div class="facility-header">Facility Profile</div>
      <p>Here at <span class='italic bold'>Because We Care</span>, we touch your loved one's life with love and care.</p>
      <p>We provide a rich program that is incorporated with tender love. Our program aims to enable the residents to maintain the highest possible social, physical and emotional balance in a caring home environment.</p>
      <p>Most of all, we offer beautiful living quarters that are safe and healthy, and 24 hour professional staff to care for the individual needs.</p>
    </div>

    <div class="services-offered two-in-row details-box">
      <div class="facility-header">Services Offered</div>
      <ul>
        <li>24 hour care and supervision</li>
        <li>Three well-balanced meals and tasty snacks</li>
        <li>Prepare special diet</li>
        <li>Supervise medication</li>
        <li>Assistance in bathing, dressing, grooming, and toileting</li>
        <li>Conduct indoor and outdoor activities</li>
        <li>Arrange transportation for medical and dental appointments</li>
        <li>Retain qualified Home Health Care Provider</li>
        <li>Provide laundry and housekeeping services</li>
      </ul>
    </div>
  </div>

  <div class="spacing"></div>

  <div class="new-row" id="row-number-2">
    <div class="facility-features two-in-row details-box">
      <div class="facility-header">Facility Features</div>
      <ul>
        <li>Quality home furnishing and wide screen</li>
        <li>Spacious 5 bedrooms</li>
        <li>Large living room</li>
        <li>Formal dining table</li>
        <li>Great patio, big backyard, and garden</li>
      </ul>
    </div>

    <div class="we-accept two-in-row details-box">
      <div class="facility-header">We Accept</div>
      <ul>
        <li>Private and Semi-private residents</li>
        <li>Incontinent of bladder and bowel</li>
        <li>Dementia &#38; Alzheimer</li>
        <li>Parkinson &#38; Diabetic</li>
      </ul>
    </div>
  </div>

  <div class="small-spacing"></div>
</div>

<div id="carousel-container">
  <div id="myCarousel" class="carousel slide">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <!-- Carousel items -->
    <div class="carousel-inner">
      <div class="active item"><img src="http://therealestateblog.files.wordpress.com/2007/08/front-of-house-web-807.jpg" alt=""></div>
      <div class="item"><img src="http://media-cdn.tripadvisor.com/media/photo-s/01/0c/62/9c/nice-room.jpg" alt=""></div>
      <div class="item"><img src="http://gottashopit.com/blog/wp-content/uploads/2013/01/Living-Room-images.jpg" alt=""></div>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
  </div>
</div>

<div class="small-spacing"></div>

<div id="contact-info">

  <h2>Our Address:</h2>
  <span class="bold">
    <p>15942 Bahama Street</p>
    <p>North Hills, CA 91343</p>
  </span>
  <p>Call Us: (818)416-6583</p>

  <div class="small-spacing"></div>

  <h2>Contact Information:</h2>
  <p>Administrator: <span class="bold">Vicky Lim<span><p>
  <p>Email: <span class="bold">vgl818@gmail.com</span></p>
  <p>Cellphone: <span class="bold">(818)416-6583</span></p>

</div>

<div id="other-location">
  <a href="/ant">
    <span class="underline"><p>Our Other Location:</p></span>
    <p>Oak Park, California</p>
  </a>
</div>

<div id="bottom-spacing"></div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>BecauseWeCare</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="container">

  <div id="title-container">
    <h1 id="homepage-title"> A Home Away From Home for Your Loved One</h1>
  </div>

  <div id='facility-links'>

      <%= link_to bwc_path, class: "homepage-text" do %>
        <div class='facility-link two-in-row'>
          <img class="facility-img" src="http://wallchips.com/wp-content/uploads/2013/12/Modern-Simple-Home-Design-2014-Wallpaper.jpg">
          Because We Care
        </div>
      <% end %>

      <%= link_to ant_path, class: "homepage-text" do %>
        <div class='facility-link two-in-row'>
          <img class="facility-img" src="http://wallchips.com/wp-content/uploads/2013/12/Modern-Simple-Home-Design-2014-Wallpaper.jpg">
          A Nurturing Touch
        </div>

      <% end %>
  </div>

</div>